
import Head from 'next/head'
import Image from 'next/image'
import CardDisplay from '../Components/Card Display/cardDisplay'
import styles from '../styles/Home.module.css'

import Map from '../Components/map'

import FilterBar from '../Components/Filter Bar/filterBar'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Untrodden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className={styles.main}>
    
    <section >
      <Map/>
    </section>
    <section>
    <CardDisplay/>
    </section>

    </main>

<FilterBar/>

      
    </div>
  )
}

