import Head from 'next/head'
import Image from 'next/image'
import CardDisplay from '../Components/Card Display/cardDisplay'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Untrodden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={styles.main}>
    <section>
      Map Place Holder
    </section>
    <section>
    <CardDisplay/>
    </section>

    </main>
      
    </div>
  )
}
